  spring:
    h2:
      console:
        enabled: true
        path: /h2-console


    datasource:
      url: jdbc:h2:mem:tmp;NON_KEYWORDS=USER
      username: sa
      password:
      driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
#         show_sql: true
          format_sql: true

    servlet:
      multipart:
        max-file-size: 5MB

  logging.level:
    org.hibernate.SQL: debug
#   org.hibernate.type: trace

  file:
    dir: C:\Users\ghkd3\work\image